# Generated by Django 6.0.1 on 2026-02-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производителя'),
        ),
        migrations.AddField(
            model_name='product',
            name='lifespan',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Срок экспуатации'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Срок гарантии'),
        ),
    ]
